 
openapi: 3.0.1
info:
  contact:
    email: hello@mainnet.cash
  description: |
    A high-level developer friendly bitcoin cash wallet api
    This API is currently in active development, breaking changes may 
    be made prior to official release of version 1.
  license:
    name: MIT Licence
    url: https://github.com/mainnet-cash/mainnet-js/blob/master/LICENSE
  termsOfService: https://mainnet.cash/terms/
  title: Mainnet Cash
  version: 0.0.3
externalDocs:
  description: Find out more about mainnet-js
  url: https://mainnet.cash
servers:
  - url: http://localhost:3000/v1
tags:
  - name: wallet
    description: Interact with wallets
    externalDocs:
      description: Find out more
      url: /api-doc/#/wallet/
paths:
  /wallet/create: 
    $ref: 'wallet.yml#/createWallet'
  /wallet/balance: 
    $ref: 'wallet.yml#/balance'    
  /wallet/deposit_address: 
    $ref: 'wallet.yml#/deposit_address'    
  /wallet/deposit_qr: 
    $ref: 'wallet.yml#/deposit_qr'    
  /wallet/max_amount_to_send: 
    $ref: 'wallet.yml#/max_amount_to_send'    
  /wallet/send: 
    $ref: 'wallet.yml#/send'
  /wallet/send_max: 
    $ref: 'wallet.yml#/send_max'
  /wallet/utxos:
    $ref: 'wallet.yml#/utxos'