openapi: 3.0.1
info:
  title: Mainnet Cash
  description: |
    A developer friendly bitcoin cash wallet api

    This API is currently in active development, breaking changes may 
    be made prior to release of version 1.

    **Important:** modifying this library to prematurely operate on mainnet
     may result in loss of funds

  termsOfService: https://mainnet.cash/terms/
  contact:
    email: hello@mainnet.cash
  license:
    name: MIT Licence 
    url: https://github.com/mainnet-cash/mainnet-js/blob/master/LICENSE
  version: 0.0.1
externalDocs:
  description: Find out more about mainnet-js
  url: https://mainnet.cash
servers:
- url: https://api.mainnet.cash/v0
tags:
- name: wallet
  description: Everything you need to manage a wallet
  externalDocs:
    description: Find out more
    url: http://mainnet.cash/docs#wallet
- name: send
  description: Send bitcoin cash
paths:
  /wallet:
    post:
      tags:
      - wallet
      summary: create a new wallet
      operationId: createWallet
      requestBody:
        description: Request a new new random wallet
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/WalletRequest'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletResponse'
        405:
          description: Invalid input
          content: {}
      security:
      - mainnet_auth:
        - write:wallet
        - read:wallet
      x-codegen-request-body-name: body
  /send:
    post:
      tags:
      - send
      summary: Send some amount to a given address
      operationId: sendRequest
      requestBody:
        description: place a send request
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/SendRequest'
        required: true
      responses:
        202:
          description: transaction accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendResponse'
        400:
          description: Invalid Request
          content: {}
        418:
          description: Invalid network for given address
          content: {}          
      security:
        - mainnet_auth:
          - write:wallet
          - read:wallet
      x-codegen-request-body-name: body
components:
  schemas:
    WalletResponse:
      type: object
      properties:
        name:
          type: string
          description: User define 
          example: username1
        type:
          type: string
          description: wallet type
          enum:
          - wif
          - hd
          example: wif
        wif:
          type: string
          description: Wallet Import Format string
          example: wif:regtest:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
        cashaddress:
          type: string
          description: The address in cashaddr format
          example: bchreg:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
        network:
          type: string
          description: network type
          enum:
          - mainnet
          - testnet
          - regtest
          example: testnet
      xml:
        name: Wallet
    WalletRequest:
      type: object
      properties:
        name:
          type: string
          description: User define 
          example: username1
        type:
          type: string
          description: wallet type
          enum:
          - wif
          - hd
          example: wif
        network:
          type: string
          description: network type
          enum:
          - mainnet
          - testnet
          - regtest
          example: testnet
      xml:
        name: Wallet        
    SendRequest:
      required:
      - wallet
      - to
      type: object
      properties:
        wallet:
          type: string
          example: regtest:abcd123
        name:
          type: string
          example: username1
      xml:
        name: SendRequest
    SendResponse:
      type: object
      properties:
        type:
          type: string
        transaction:
          type: string
  securitySchemes:
    mainnet_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://auth.mainnet.cash
          scopes:
            write:wallet: modify your account
            read:wallet: view your wallet