name: Generate

on:
  push:
    paths:
      - "swagger/v1/*.yml"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Validate Specification
        uses: 2qx/codegen-docker-action@v1
        with:
          args: |
            validate -i swagger/v1/api.yml
      - name: Generate Mock Client
        uses: 2qx/codegen-docker-action@v1
        with:
          args: |
            generate -i swagger/v1/api.yml -g typescript-node -o generated/client/typescript-mock
      - name: Generate Server
        uses: 2qx/codegen-docker-action@v1
        with:
          args: |
            generate -i swagger/v1/api.yml -g typescript-express-server -o generated/serve
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Update generated
